# Generated by Django 5.2.17 on 2026-08-26 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('color', models.CharField(max_length=20)),
                ('bg_type', models.CharField(choices=[('gradient', 'Gradient'), ('color', 'Color'), ('image', 'Image')], default='gradient', max_length=10)),
                ('bg_value', models.TextField(blank=True, default='')),
                ('music_url', models.URLField(blank=True, default='')),
                ('music_name', models.CharField(blank=True, default='ninguna', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('progress', 'In Progress'), ('waiting', 'Waiting'), ('done', 'Completed')], default='pending', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True, default='')),
                ('date', models.CharField(blank=True, default='', max_length=10)),
                ('time', models.CharField(blank=True, default='', max_length=5)),
                ('pomos', models.PositiveIntegerField(default=0)),
                ('done_at', models.CharField(blank=True, default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='boards.board')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('board_name', models.CharField(max_length=120)),
                ('color', models.CharField(max_length=20)),
                ('minutes', models.PositiveIntegerField()),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to='boards.board')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to='boards.card')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_from', models.CharField(max_length=10)),
                ('date_to', models.CharField(max_length=10)),
                ('days', models.JSONField(default=dict)),
                ('count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='boards.board')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
