# Generated by Django 5.2.17 on 2026-08-26 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('moved', 'Moved')], max_length=10)),
                ('detail', models.CharField(blank=True, default='', max_length=300)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='boards.card')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
