# Generated by Django 5.2.17 on 2026-08-27 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_card_status_cardnote_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='routine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='boards.routine'),
        ),
        migrations.AddField(
            model_name='routine',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
